Backend/diet/urls.py
# urls.py
from django.urls import path,include
from . import views

app_name = 'diet'
urlpatterns = [
    path('food_types/', views.list_food_types, name='list_food_types'),
    path('food/', views.get_food_list, name='food_list'),
    path('create/', views.create_meal, name='create_meal'),
    path('', views.get_meal_list, name='meal_list'),
    path('<int:meal_id>/', views.get_meal, name='meal_detail'),
    # path('<str:food_name>/', views.get_meal, name='meal_by_food_name'),
    path('<int:meal_id>/update/', views.update_meal, name='update_meal'),
    path('<int:meal_id>/delete/', views.delete_meal, name='meal_delete'),
    path('daily_summary/', views.get_daily_summary, name='get_calorie_info'),
    path('step_history/', views.get_step_history, name='get_step_history'),
    path ('nutrition/' , views.calculate_nutrition_by_portion , name='calculate_nutrition_by_portion'),
    path('calorie_summary/', views.calorie_summary, name='calorie-summary'),
    path('nutrition_summary/', views.nutrition_summary, name='nutrition_summary'),
    path('record_cumulative_steps/', views.record_cumulative_steps, name='record_cumulative_steps'),
    path('steps_today/', views.get_today_step_record, name='get_today_step_record'),
    # path('', include('diet.formss.urls')),
]

Backend/medication/urls.py
from django.urls import path
from . import views

app_name = 'medication'

urlpatterns = [
    path('', views.get_medications, name='list_medications'),
    path('<int:primary_key>/', views.get_medication, name='get_medication'),
    path('create/', views.create_medication, name='create_medication'),
    path('update/<int:primary_key>/', views.update_medication, name='update_medication'),
    path('delete/<int:primary_key>/', views.delete_medication, name='delete_medication'),
    path('active_medications/', views.get_active_medications, name='get_active_medications'),
    path('today_upcoming/', views.get_todays_upcoming_medications, name='get_todays_upcoming_medications'),
    path('medication_day/', views.get_medications_on_day, name='get_medications_on_day'),

]

Backend/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib import admin
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.conf import settings




schema_view = get_schema_view(
    openapi.Info(
        title="",
        default_version='v1',),
    public=True,
    permission_classes=(permissions.AllowAny,),
)



urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('social_accounts.urls')),
    path('admin/', admin.site.urls),
    path('diabetis/' , include(('diabetis.urls' , 'diabetis') , namespace = 'diabetis')),
    path('chatbot/', include(('chatbot.urls', 'chatbot'), namespace='chatbot')),
    path('api/login/', LoginView.as_view(), name='api_login'),
    path('diet/', include(('diet.urls'), namespace='diet')),
    path('medication/', include(('medication.urls'), namespace='medication')),
    path('footcare/', include(('footcare.urls'), namespace='footcare')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0),name='schema-swagger-ui'),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Backend/medication/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone

class Medication(models.Model):
    ROUTE_CHOICES = (
        ('oral', 'Orally'),
        ('parentral/im', 'Intra-muscular'),
        ('parentral/iv', 'Intravenous'),
        ('parentral/sc', 'Subcutaneous'),
    )

    UNIT_CHOICES = (
        ('tablet', 'Tablet'),
        ('capsule', 'Capsule'),
        ('gravimetric/mg', 'Milligram (mg)'),
        ('volumetric/ml', 'Milliliter/ml'),
    )

    INTERVAL_CHOICES = (
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
    )
    
    FORM_DOSAGE = (
        ('tablet', 'Tablet'), 
        ('capsule', 'Capsule'), 
        ('syrup', 'Syrup'), 
        ('injectable', 'Injectable')
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='medications')
    medication_name = models.CharField(max_length=100, help_text="Generic name of the medication")
    route_of_administration = models.CharField(max_length=50, choices=ROUTE_CHOICES, default='oral')
    dosage_form = models.CharField(max_length=50, choices=FORM_DOSAGE, default='syrup')
    dosage_unit_of_measure = models.CharField(max_length=50, choices=UNIT_CHOICES, default='tablet')
    dosage_quantity_of_units_per_time = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    interaction_warning = models.CharField(max_length=512, null=True, blank=True)
    equally_distributed_regimen = models.BooleanField(default=True, null=True, blank=False)
    dosage_frequency = models.PositiveIntegerField()
    periodic_interval = models.CharField(max_length=20, choices=INTERVAL_CHOICES, default='daily')
    first_time_of_intake = models.DateTimeField(default=timezone.now)
    stopped_by_datetime = models.DateTimeField(null=True, blank=True)
    
    
    def __str__(self):
        return self.medication_name
    
    def calculate_next_dose(self):
        """
        Calculate the next dose based on the first time of intake and the periodic interval.
        """
        if self.periodic_interval == 'daily':
            return self.first_time_of_intake + timezone.timedelta(days=self.dosage_frequency)
        elif self.periodic_interval == 'weekly':
            return self.first_time_of_intake + timezone.timedelta(weeks=self.dosage_frequency)
        elif self.periodic_interval == 'monthly':
            return self.first_time_of_intake + timezone.timedelta(weeks=4 * self.dosage_frequency)
        return self.first_time_of_intake
    


    

Backend/medication/views.py
#medication/view.py

from django.http import JsonResponse
from .models import Medication
from .serializers import MedicationSerializer
from drf_yasg.utils import swagger_auto_schema
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from django.conf import settings
import joblib
import numpy as np
import json
from drf_yasg import openapi
from django.db.models import Q
from django.utils import timezone
from datetime import timedelta, time ,datetime
from dateutil import parser
from .utils import get_todays_scheduled_doses
import pytz

#Load model and matrices
clf = joblib.load(settings.DRUG_INTERACTION_MODEL_PATH)
u = np.load(settings.U_MATRIX_PATH)
vt = np.load(settings.VT_MATRIX_PATH)
drug_index = np.load(settings.DRUG_INDEX_PATH, allow_pickle=True).item()

# Severity Mapping for drug interactions
severity_messages = {
    3: "Major interaction: Serious side effects may occur. Consult a healthcare provider.",
    2: "Moderate interaction: Potential interactions. Seek medical advice if needed.",
    1: "Minor interaction: Minimal effects expected.",
    0: "No known interaction."
}

# Function to preprocess input data for drug interaction prediction
def preprocess_input(drug_a, drug_b):
    """Prepare input features for prediction."""
    idx1 = drug_index.get(drug_a)
    idx2 = drug_index.get(drug_b)
    if idx1 is None or idx2 is None:
        return None
    return np.concatenate([u[idx1], vt[idx2]])

# Function to predict the severity of a drug interaction
def predict_interaction(drug_a, drug_b):
    """Predict severity of drug interaction."""
    features = preprocess_input(drug_a, drug_b)
    if features is None:
        return None
    severity_prediction = clf.predict([features])[0]
    return severity_messages.get(severity_prediction, "Unknown interaction level.")

# Function to format medication name
def format_medication_name(name):
    return name.strip().lower().capitalize() if name else name


def parse_datetime_safe(raw_value):
    if not raw_value:
        return None
    
    try:
        dt = parser.isoparse(raw_value)
        if timezone.is_naive(dt):
            # If naive, assume UTC
            return timezone.make_aware(dt, pytz.UTC)
        # If aware, convert to UTC
        return dt.astimezone(pytz.UTC)
    except ValueError:
        return None

# 1. Function to create a new medication entry and check for interactions with existing medications
@swagger_auto_schema(method='post', request_body=MedicationSerializer, responses={201: MedicationSerializer, 400: 'Bad Request'})
@api_view(['POST'])
@permission_classes([IsAuthenticated])
def create_medication(request):
    data = request.data
    medication_name = format_medication_name(data.get('medication_name'))
    
    if not medication_name:
        return Response({"error": "Medication name is required."}, status=400)

    # Check interactions with existing medications
    interaction_warnings = {}

    current_time = timezone.now()
    
    existing_medications = Medication.objects.filter(
        user=request.user
    ).filter(
        Q(stopped_by_datetime__gte=current_time) | Q(stopped_by_datetime__isnull=True)
    )
    
    for med in existing_medications:
        existing_med_name = format_medication_name(med.medication_name)
        interaction_result = predict_interaction(existing_med_name, medication_name)
        if interaction_result:
            interaction_warnings[med.medication_name] = interaction_result

    first_time = parse_datetime_safe(data.get('first_time_of_intake'))
    stopped_time = parse_datetime_safe(data.get('stopped_by_datetime'))

    medication = Medication.objects.create(
        user=request.user,
        medication_name=medication_name,
        route_of_administration=data.get('route_of_administration', 'oral'),
        dosage_form=data.get('dosage_form', 'tablet'),
        dosage_unit_of_measure=data.get('dosage_unit_of_measure', 'tablet'),
        dosage_quantity_of_units_per_time=data.get('dosage_quantity_of_units_per_time', 1),
        equally_distributed_regimen=True,
        periodic_interval=data.get('periodic_interval', 'daily'),
        dosage_frequency=data.get('dosage_frequency', 1),
        first_time_of_intake=first_time,
        stopped_by_datetime=stopped_time,
        interaction_warning=interaction_warnings,
    )

    serializer = MedicationSerializer(medication)
    return Response(serializer.data, status=201)

# 2. Function to update an existing medication entry and check for interactions with other medications
@swagger_auto_schema(method='put', request_body=MedicationSerializer, responses={200: MedicationSerializer, 400: 'Bad Request', 404: 'Not Found'})
@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def update_medication(request, primary_key):
    """Update an existing medication."""
    try:
        medication = Medication.objects.get(id=primary_key, user=request.user)
    except Medication.DoesNotExist:
        return Response({"error": "Medication not found."}, status=404)

    data = request.data
    medication_name = format_medication_name(data.get('medication_name', medication.medication_name))

    # Check interactions
    interaction_warnings = {}
    current_time = timezone.now()
    existing_medications = Medication.objects.filter(
        user=request.user
    ).filter(
        Q(stopped_by_datetime__gte=current_time) | Q(stopped_by_datetime__isnull=True)
    )

    for med in existing_medications:
        interaction_result = predict_interaction(med.medication_name, medication_name)
        if interaction_result:
            interaction_warnings[med.medication_name] = interaction_result

    # Parse datetime fields safely using your function
    first_time = parse_datetime_safe(data.get('first_time_of_intake'))
    stopped_time = parse_datetime_safe(data.get('stopped_by_datetime'))

    # Update medication fields
    medication.medication_name = medication_name
    medication.route_of_administration = data.get('route_of_administration', medication.route_of_administration)
    medication.dosage_form = data.get('dosage_form', medication.dosage_form)
    medication.dosage_unit_of_measure = data.get('dosage_unit_of_measure', medication.dosage_unit_of_measure)
    medication.dosage_quantity_of_units_per_time = data.get('dosage_quantity_of_units_per_time', medication.dosage_quantity_of_units_per_time)
    medication.equally_distributed_regimen = data.get('equally_distributed_regimen', medication.equally_distributed_regimen)
    medication.periodic_interval = data.get('periodic_interval', medication.periodic_interval)
    medication.dosage_frequency = data.get('dosage_frequency', medication.dosage_frequency)
    medication.first_time_of_intake = first_time or medication.first_time_of_intake
    medication.stopped_by_datetime = stopped_time or medication.stopped_by_datetime
    medication.interaction_warning = interaction_warnings

    medication.save()

    serializer = MedicationSerializer(medication, context={'user_timezone': request.user_timezone})
    return Response(serializer.data, status=200)


# 3. Function to retrieve all medications for the authenticated user
@swagger_auto_schema(method='get', responses={200: MedicationSerializer(many=True)})
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_medications(request):
    """Retrieve all medications for the authenticated user."""
    medications = Medication.objects.filter(user=request.user)
    serializer = MedicationSerializer(medications, many=True,context={'user_timezone': request.user_timezone})
    return Response(serializer.data)


# 4. Function to retrieve a specific medication entry for the authenticated user
@swagger_auto_schema(method='get', responses={200: MedicationSerializer})
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_medication(request, primary_key):
    """Retrieve a specific medication."""
    try:
        medication = Medication.objects.get(id=primary_key, user=request.user )
    except Medication.DoesNotExist:
        return Response({"error": "Medication not found."}, status=404)
    
    serializer = MedicationSerializer(medication ,context={'user_timezone': request.user_timezone})
    return Response(serializer.data)

# 5. Function to retrieve all active medications for the authenticated user
@swagger_auto_schema(method='get', responses={200: MedicationSerializer(many=True)})
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_active_medications(request):
    """Retrieve all active medications for the authenticated user."""
    # Get current time
    user_tz = request.user_timezone
    current_time = timezone.now().astimezone(user_tz)

    # Filter medications where stopped_by_datetime is None or in the future
    active_medications = Medication.objects.filter(
        user=request.user
    ).filter(
        Q(stopped_by_datetime__gte=current_time) | Q(stopped_by_datetime__isnull=True)
    )
    
    serializer = MedicationSerializer(active_medications, many=True ,context={'user_timezone': request.user_timezone})
    return Response(serializer.data)


# 6. Function to delete a medication entry for the authenticated user
@swagger_auto_schema(method='delete', responses={204: 'No Content'})
@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def delete_medication(request, primary_key):
    """Delete a medication."""
    try:
        medication = Medication.objects.get(id=primary_key, user=request.user)
    except Medication.DoesNotExist:
        return Response({"error": "Medication not found."}, status=404)

    medication.delete()
    return Response({"message": "Medication deleted successfully."}, status=204)

@swagger_auto_schema(method='get', responses={200: 'List of upcoming medications for a specific day'})
@api_view(['GET'])
def get_medications_on_day(request):

Backend/medication/templates/medications/input_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drug Interaction Prediction</title>
</head>
<body>
    <h2>Drug Interaction Prediction</h2>
    <form id="predictionForm">
        <label for="drug_a">Enter Drug 1:</label><br>
        <input type="text" id="drug_a" name="drug_a"><br><br>
        <label for="drug_b">Enter Drug 2:</label><br>
        <input type="text" id="drug_b" name="drug_b"><br><br>
        <button type="button" onclick="submitForm()">Submit</button>
    </form>
    <div id="result"></div>
    
    <script>
        function submitForm() {
            const drugA = document.getElementById('drug_a').value;
            const drugB = document.getElementById('drug_b').value;
    
            fetch('/predict/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ drug_a: drugA, drug_b: drugB })
            })
            .then(response => response.json())
            .then(data => {
                if (data.error) {
                    document.getElementById('result').innerHTML = `<p style="color:red;">${data.error}</p>`;
                } else {
                    document.getElementById('result').innerHTML = `<p>${data.severity}</p>`;
                }
            })
            .catch(error => {
                document.getElementById('result').innerHTML = `<p style="color:red;">An error occurred: ${error}</p>`;
            });
        }
    </script>
    

Backend/medication/templates/medications/medication_confirm_delete.html
{% block content %}
  <h1>Are you sure you want to delete this medication?</h1>
  <p>{{ medication.medication_name }} - {{ medication.route_of_administration }}</p>
  
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
  
  <a href="{% url 'medication:medication_list' %}">Cancel</a>
{% endblock %}

Backend/medication/templates/medications/medication_detail.html
{% block content %}
  <h1>{{ medication.medication_name }}</h1>
  
  <p><strong>Route:</strong> {{ medication.route_of_administration }}</p>
  <p><strong>Dosage:</strong> {{ medication.dosage_quantity_of_units_per_time }} {{ medication.dosage_unit_of_measure }}</p>
  <p><strong>Dosage Form:</strong> {{ medication.dosage_form }}</p>
  <p><strong>Frequency:</strong> {{ medication.dosage_frequency }} times per {{ medication.get_periodic_interval_display }}</p>
  <p><strong>First Intake:</strong> {{ medication.first_time_of_intake|date:"Y-m-d H:i" }}</p>
  <p><strong>interaction_warning:</strong> {{ medication.interaction_warning }}</p>
  <p><strong>Status:</strong> 

    {% if medication.is_active %}
      Active
    {% else %}
      Inactive
    {% endif %}
  </p>

  <!-- Display interaction warning if it exists -->
  {% if medication.interaction_warning %}
    <div class="alert alert-warning">
      <strong>Interaction Warning:</strong> {{ medication.interaction_warning }}
    </div>
  {% endif %}

  <!-- Links to edit or delete medication -->
  <a href="{% url 'medication:medication_edit' medication.id %}" class="btn btn-warning">Edit</a>
  <a href="{% url 'medication:medication_delete' medication.id %}" class="btn btn-danger">Delete</a>
  <a href="{% url 'medication:medication_list' %}" class="btn btn-primary">Back to List</a>
{% endblock %}

Backend/medication/templates/medications/medication_form.html
{% block content %}
  <h1>{% if form.instance.medication_name %}Update Medication{% else %}Create Medication{% endif %}</h1>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
  
  <a href="{% url 'medication:medication_list' %}">Cancel</a>
{% endblock %}

Backend/medication/templates/medications/medication_list.html
{% block content %}
  <h1>My Medications</h1>
  <a href="{% url 'medication:medication_create' %}">Add New Medication</a>
  <ul>
    {% for medication in medications %}
      <li>
        <a href="{% url 'medication:medication_detail' medication.id %}">{{ medication.medication_name }}</a>
        - {{ medication.first_time_of_intake }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}